- hosts: all
  become: true
  tasks: 
     - name: delete old deployment
       command: kubectl delete -f /home/azureuser/Deployment.yaml
     - name: delete old service
       command: kubectl delete -f /home/azureuser/Service.yaml
     - name: create new deployment
       command: kubectl apply -f /home/azureuser/Deployment.yaml
     - name: create new service
       command: kubectl apply -f /home/azureuser/Service.yaml
