apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8proj-deployment
  namespace: default
  labels:
    app: betaverse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: betaverse
  template:
    metadata:
      labels:
        app: betaverse
    spec:
      containers:
      - name: betaverse
        image: tekshare/k8proj:beta
        ports:
        - containerPort: 80
