apiVersion: v1
kind: Service
metadata:
  name: k8proj-service
spec:
  selector:
    app.kubernetes.io/name: betaverse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31200
  type: LoadBalancer
